backend:
  name: git-gateway
  branch: main # Reemplaza con el nombre de la rama principal de tu repositorio

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'articulos'
    label: 'Artículos'
    folder: 'content/articulos'
    create: true
    fields:
      - { label: 'Título', name: 'titulo', widget: 'string' }
      - { label: 'Categoría', name: 'categoria', widget: 'select', options: ['Política', 'River Plate'] }
      - { label: 'Resumen', name: 'resumen', widget: 'text' }
      - { label: 'Imagen', name: 'imagen', widget: 'image' }
      - { label: 'Contenido', name: 'contenido', widget: 'markdown' }
